default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: koala_db

test:
  <<: *default
  database: koala_test

production:
  <<: *default
  database: koala_prod
