# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.8'

gem 'bootsnap', require: false
gem 'dotenv-rails'
gem 'pg', '~> 1.1'
gem 'prometheus_exporter'
gem 'puma', '>= 5.0'
gem 'rack-attack'
gem 'rack-cors'
gem 'rails', '~> 7.1.5', '>= 7.1.5.1'
gem 'redis'
gem 'ruby-kafka'
gem 'tzinfo-data', platforms: %i[windows jruby]
gem 'whenever', require: false

group :development, :test do
  gem 'brakeman', require: false
  gem 'erb_lint', require: false
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'rswag'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end
