source "https://rubygems.org"

ruby "3.2.8"

gem "rails", "~> 7.1.5", ">= 7.1.5.1"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem "rack-attack"
gem "redis"
gem "dotenv-rails"
gem "ruby-kafka"
gem "whenever", require: false
gem 'rack-cors'

group :development, :test do
  gem 'rspec-rails'
  gem 'rswag'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'dotenv-rails'
  gem 'pry-rails'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'brakeman', require: false
  gem 'erb_lint', require: false
end

