{
 "title": "Rails App Metrics",
 "refresh": "10s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(ruby_http_requests_total)" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_request_duration_seconds_sum[1m])) / sum(rate(ruby_http_request_duration_seconds_count[1m]))",
     "legendFormat": "avg duration"
    }
   ]
  },
  {
   "title": "SQL Request Duration",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(ruby_http_request_sql_duration_seconds_sum[1m])) / sum(rate(ruby_http_request_sql_duration_seconds_count[1m]))",
     "legendFormat": "SQL avg"
    }
   ]
  },
  {
   "title": "Active Web Processes",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 6, "h": 4 },
   "targets": [
    { "expr": "ruby_collector_working" }
   ]
  },
  {
   "title": "Memory (RSS)",
   "type": "stat",
   "gridPos": { "x": 18, "y": 8, "w": 6, "h": 4 },
   "format": "bytes",
   "targets": [
    { "expr": "ruby_collector_rss" }
   ]
  }
 ]
}